// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace scripts
{
public static class GPGIds
{
        public const string achievement_precision_30 = "CgkI363G7ewOEAIQCg"; // <GPGSID>
        public const string achievement_500_kills = "CgkI363G7ewOEAIQBA"; // <GPGSID>
        public const string achievement_precision_20 = "CgkI363G7ewOEAIQCQ"; // <GPGSID>
        public const string achievement_precision_10 = "CgkI363G7ewOEAIQCA"; // <GPGSID>
        public const string achievement_three_for_one = "CgkI363G7ewOEAIQBg"; // <GPGSID>
        public const string achievement_two_for_one = "CgkI363G7ewOEAIQBQ"; // <GPGSID>
        public const string achievement_four_for_0ne = "CgkI363G7ewOEAIQBw"; // <GPGSID>
        public const string achievement_200_kills = "CgkI363G7ewOEAIQAw"; // <GPGSID>
        public const string achievement_100_kills = "CgkI363G7ewOEAIQAg"; // <GPGSID>
        public const string leaderboard_score = "CgkI363G7ewOEAIQAQ"; // <GPGSID>

}
}
